### ISSUE TITLE
Is there any publications?

### ISSUE THREAD

**Issue by hmf17** [ovysotska/image_sequence_localizer#10]
Hi @ovysotska , thanks for sharing such impressive works.
Do you have any publications or papers about the "Sequence Localizer"? I am very interested about the "Sequence" style for recognition rather than the single queried image.
Looking forward to your reply!

**Comment by ovysotska** [comment]
Hi @hmf17, thanks for your interest in this project :smile: 
Yes, there are a couple of publications that describe this work in more detail.
**The base one**, where the graph construction and the meaning of the nodes are explained in detail is [Online Place recognition]( http://www.ipb.uni-bonn.de/pdfs/vysotska16ral-icra.pdf).
The relocalization stage, in the case the robot gets lost completely, is roughly described here [Relocalization](https://www.ipb.uni-bonn.de/wp-content/papercite-data/pdf/vysotska2017irosws.pdf).
The relocalization is needed when the robot visits an area that was not mapped before. In the case, of pure image sequences. this would be the case when the query sequence contains images of the places that were never seen in the reference sequence.

**Comment by hmf17** [comment]
Hi @ovysotska 
You mention that the relocalization will work when robot goes beyond the map. In my opinion, is that mean the relocalization will rectify the trajectory when the robot goes back from an unknown area to a mapped area?  Because in an un-mapped area, it seems improssible to perform such visual localization algorithm.

**Comment by ovysotska** [comment]
Hi,
great question!
Let me clarify here a bit on notation that I am using.
I call the "normal" sequence-to-sequence matching process as **localization**. This happens when the query and the reference sequence follow the same route in the environment.
When the query trajectory "goes to unknown" place or the place that was not seen in the reference sequence, the localization in the previous sense is not possible. Exactly the way you said in your comment. In this case, we deploy **relocalization**. 
In relocalization in contrast to localization we use a hashing technique to roughly figure out if the query trajectory "has returned" to a place covered by the reference trajectory, meaning if it has returned to the mapped area. Once this happens, the "localization" starts again. And if I understood correctly what you mean, then yes the localization "will rectify" or correct the found image correspondences.
Please let me know if this answers your question :smile: .

**Comment by hmf17** [comment]
Hi @ovysotska 
Great thanks to your reply in detail, it is very helpful! I am in agreement with the your notaion above and it sovled my question.
I will intently read your papers to learn more about this pipeline.

**Comment by ovysotska** [comment]
Great, let me know if you have further questions.
