### ISSUE TITLE
Does it work with different start point between query and reference?

### ISSUE THREAD

**Issue by cswwp** [ovysotska/image_sequence_localizer#35]
Hi, @ovysotska , in my work scene, i need to make relocalization in any start point (maybe this start point never occur in reference, and it arrivals one place which occur in reference after fews of continious frame), and i imitate this scene with delete first N frames in reference set, and then cause start point mismatch between query and reference. But after run demo, the result is bad, and it occurs may dismatched pair as follows. In my thinking, it caused by accumulated error by start point error match.  Do you mind to explain why this happen? and any advice to prevent this case ?  Thank you

![img_v3_02ce_b521f4da-d86b-4ee7-958c-8c693fcf483g](https://github.com/ovysotska/image_sequence_localizer/assets/11901683/e4c31b2a-5a02-4c59-a832-7c83aece008c)
![img_v3_02ce_899d4dea-4c20-41b4-8369-16e49c30c48g](https://github.com/ovysotska/image_sequence_localizer/assets/11901683/7f771d69-5d87-4169-b699-226ca402033a)
![img_v3_02ce_94612af6-ee47-496c-80aa-28322171ce6g](https://github.com/ovysotska/image_sequence_localizer/assets/11901683/34a5a4d5-88e5-4b08-bb25-21e8669e6b3b)

**Comment by ovysotska** [comment]
Hey @cswwp ,

sorry, I just noticed this issue.
yes, it should work if you delete the first N frames in the reference sequence.
Could you provide a picture of the cost matrix and matching result? The demo code should generate it by default.

**Comment by cswwp** [comment]
> Hey @cswwp ,
> 
> sorry, I just noticed this issue. yes, it should work if you delete the first N frames in the reference sequence. Could you provide a picture of the cost matrix and matching result? The demo code should generate it by default.

Hi @ovysotska 
![image](https://github.com/user-attachments/assets/5886a0b2-c9cc-4b18-975d-6cd69ff6e926)
![image](https://github.com/user-attachments/assets/adcd57df-31a0-461f-afa7-165d154f825a)

First row image is my sequence cost image. Second row image is the route line of reference and query, seems it degenerated by the area which have no key frame in reference dataset.

**Comment by ovysotska** [comment]
Hey, 
thanks for providing the details.

This search algorithm, as a lot of other visual place recognition approaches, relies on the parameter, here called `nonMatchCost`. This is the parameter that determines if two images represent the same place or not based on a chosen metric. This can be seen also as a threshold.
If you run the code starting from the provided demo `python run_matching.py ...` this parameter gets set automatically for you, see this line in the code
https://github.com/ovysotska/image_sequence_localizer/blob/1ab5de346341eab6c6a4e56e9a10c4974c1adbce/src/python/run_matching.py#L61

The problem is that the default value (3.7) of the `nonMatchCost` is not ideal for your example. It is too high.
I suggest gradually decreasing the value to 1.0.  If you set the value close to 1.0, the resulting image will have the path marked in blue, and no image matches will be reported. This means that the nonMatchCost is too low.

If you choose a value and start seeing a few blue pixels in the path, the path should jump from one place to another correct place.

Let me know if this doesn't work.

**Comment by cswwp** [comment]
@ovysotska Hey, it works now with modify the parameter, thanks for your patient help. 💯 😸

**Comment by ovysotska** [comment]
Happy it worked for you!
