### ISSUE TITLE
Question of node expand strategy in the papepr

### ISSUE THREAD

**Issue by Wuqiqi123** [ovysotska/image_sequence_localizer#36]
![](https://i.meee.com.tw/ctOVqXG.png)
Hi, @ovysotska, Thanks for sharing your work of vpr.
When I'm reading the paper, I have a questions of picture show in paper. 
Why the blue node(with a low similarity) is chosen to expand?

**Comment by ovysotska** [comment]
Hi,

The blue node is chosen to be expanded because at timepoint 1, it represents the `best matching hypothesis`. Meaning that the path that leads to this node is the shortest path among all the path considered till timestamp 1.

The color blue indeed indicates that the similarity value between the query image 1 and the corresponding reference image is low, but it might be that the shortest path still lies through this node, that it indeed represent the same place. It can occur when for example the car passes before the camera and obstructs the view for 1 frame. Then the similarity will be low, however, it is still the same place.

**Comment by Wuqiqi123** [comment]
Thanks for detailed explain. But I'm also confused about shortest path.
![](https://i.meee.com.tw/Eio6OwM.png)
As shown in the picture, the red arrow path is always shorter than the cyan arrow path because the green node is more similar than the blue node in layer 1 . As we know that the dijkstra shortest path is a greedy algorithm. So Why we can't choose most similar node in each layer of query image sequence? @ovysotska

**Comment by ovysotska** [comment]
Hey,

I am afraid there is a small misunderstanding here. The green node only marks the fact that this node was expanded, in other words added to the graph. The circles that are dashed are the ones that were not considered to be added to the graph, however, they would be added in  previous paper.

The red and blue nodes denote the nodes that are the part of the shortest path. 
So the green only shows that the node is in the graph. Both red and blue nodes are also green nodes.

Does this bring more clarity?

**Comment by Wuqiqi123** [comment]
Got it. Thank you very much
